<Project>

  <ItemGroup>
    <!-- VisionSharp -->
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.2.0" />
    <PackageVersion Include="MathNet.Numerics" Version="5.0.0" />
    <PackageVersion Include="Numpy" Version="3.11.1.33" />
    <PackageVersion Include="OpenCvSharp4" Version="4.7.0.20230115" />
    <PackageVersion Include="OpenCvSharp4.runtime.win" Version="4.7.0.20230115" />
    <PackageVersion Include="System.Drawing.Common" Version="10.0.11" />
    <PackageVersion Include="ZXing.Net" Version="0.16.11" />
    <PackageVersion Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.16" />
    <PackageVersion Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" />

    <!-- UnitTest -->
    <PackageVersion Include="FluentAssertions" Version="6.11.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.5.0" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageVersion Include="xunit" Version="2.4.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.4.5" />
    <PackageVersion Include="coverlet.collector" Version="3.2.0" />
  </ItemGroup>

</Project>
